[build]
  publish = "_site"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Netlify Identity redirects
[[redirects]]
  from = "/.netlify/identity/*"
  to = "/.netlify/identity/:splat"
  status = 200

# Redirect admin to the admin panel
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

# Handle SPA routing for the map
[[redirects]]
  from = "/map/*"
  to = "/map/index.html"
  status = 200

# Handle wiki routing
[[redirects]]
  from = "/wiki/*"
  to = "/wiki/index.html"
  status = 200

# Fallback for any other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404