backend:
  name: git-gateway
  branch: main

site_url: https://nimea-wiki.netlify.app

media_folder: "images"
public_folder: "/images"

# Simple publish mode - changes go live immediately
publish_mode: simple

collections:
  # Turkish Collections
  - name: "player-characters"
    label: "Player Characters (TR)"
    folder: "wiki/player-characters"
    create: true
    identifier_field: "slug"
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "URL-friendly version of the name" }
      - { label: "Summary", name: "summary", widget: "text", hint: "A brief description" }
      - { label: "Cover Image", name: "cover_image", widget: "image", required: false }
      - { label: "Public", name: "public", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "characters"
    label: "Characters (TR)"
    folder: "wiki/characters"
    create: true
    identifier_field: "slug"
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "URL-friendly version of the name" }
      - { label: "Summary", name: "summary", widget: "text", hint: "A brief description" }
      - { label: "Cover Image", name: "cover_image", widget: "image", required: false }
      - { label: "Public", name: "public", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "nations-factions"
    label: "Nations & Factions (TR)"
    folder: "wiki/nations-factions"
    create: true
    identifier_field: "slug"
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "URL-friendly version of the name" }
      - { label: "Summary", name: "summary", widget: "text", hint: "A brief description" }
      - { label: "Cover Image", name: "cover_image", widget: "image", required: false }
      - { label: "Public", name: "public", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "locations-regions"
    label: "Locations & Regions (TR)"
    folder: "wiki/locations-regions"
    create: true
    identifier_field: "slug"
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "URL-friendly version of the name" }
      - { label: "Summary", name: "summary", widget: "text", hint: "A brief description" }
      - { label: "Cover Image", name: "cover_image", widget: "image", required: false }
      - { label: "Map ID", name: "map_id", widget: "string", required: false, hint: "Link to map marker" }
      - { label: "Public", name: "public", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "gods-religions"
    label: "Gods & Religions (TR)"
    folder: "wiki/gods-religions"
    create: true
    identifier_field: "slug"
    slug: "{{slug}}"
    filter:
      field: type
      value: deity
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "URL-friendly version of the name" }
      - { label: "Summary", name: "summary", widget: "text", hint: "A brief description" }
      - { label: "Cover Image", name: "cover_image", widget: "image", required: false }
      - { label: "Portrait Image", name: "portrait_image", widget: "image", required: false }
      - { label: "Public", name: "public", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "magic-powers"
    label: "Magic & Powers (TR)"
    folder: "wiki/magic-powers"
    create: true
    identifier_field: "slug"
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "URL-friendly version of the name" }
      - { label: "Summary", name: "summary", widget: "text", hint: "A brief description" }
      - { label: "Cover Image", name: "cover_image", widget: "image", required: false }
      - { label: "Public", name: "public", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

  # English Collections
  - name: "en-player-characters"
    label: "Player Characters (EN)"
    folder: "en/wiki/player-characters"
    create: true
    identifier_field: "slug"
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "URL-friendly version of the name" }
      - { label: "Summary", name: "summary", widget: "text", hint: "A brief description" }
      - { label: "Cover Image", name: "cover_image", widget: "image", required: false }
      - { label: "Public", name: "public", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "en-characters"
    label: "Characters (EN)"
    folder: "en/wiki/characters"
    create: true
    identifier_field: "slug"
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "URL-friendly version of the name" }
      - { label: "Summary", name: "summary", widget: "text", hint: "A brief description" }
      - { label: "Cover Image", name: "cover_image", widget: "image", required: false }
      - { label: "Public", name: "public", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "en-nations-factions"
    label: "Nations & Factions (EN)"
    folder: "en/wiki/nations-factions"
    create: true
    identifier_field: "slug"
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "URL-friendly version of the name" }
      - { label: "Summary", name: "summary", widget: "text", hint: "A brief description" }
      - { label: "Cover Image", name: "cover_image", widget: "image", required: false }
      - { label: "Public", name: "public", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "en-locations-regions"
    label: "Locations & Regions (EN)"
    folder: "en/wiki/locations-regions"
    create: true
    identifier_field: "slug"
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "URL-friendly version of the name" }
      - { label: "Summary", name: "summary", widget: "text", hint: "A brief description" }
      - { label: "Cover Image", name: "cover_image", widget: "image", required: false }
      - { label: "Map ID", name: "map_id", widget: "string", required: false, hint: "Link to map marker" }
      - { label: "Public", name: "public", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "en-gods-religions"
    label: "Gods & Religions (EN)"
    folder: "en/wiki/gods-religions"
    create: true
    identifier_field: "slug"
    slug: "{{slug}}"
    filter:
      field: type
      value: deity
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "URL-friendly version of the name" }
      - { label: "Summary", name: "summary", widget: "text", hint: "A brief description" }
      - { label: "Cover Image", name: "cover_image", widget: "image", required: false }
      - { label: "Portrait Image", name: "portrait_image", widget: "image", required: false }
      - { label: "Public", name: "public", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

  # Hub pages as single-file entries so they don't inherit deity-required fields
  - name: "gods-religions-hub-tr"
    label: "Gods & Religions Hub (TR)"
    files:
      - label: "TR: Gods & Religions Hub"
        name: "gods-religions-hub-tr"
        file: "wiki/gods-religions/index.md"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Summary", name: "summary", widget: "text", required: false }
          - { label: "Cover Image", name: "cover_image", widget: "image", required: false }

  - name: "gods-religions-hub-en"
    label: "Gods & Religions Hub (EN)"
    files:
      - label: "EN: Gods & Religions Hub"
        name: "gods-religions-hub-en"
        file: "en/wiki/gods-religions/index.md"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Language", name: "lang", widget: "hidden", default: "en" }
          - { label: "Summary", name: "summary", widget: "text", required: false }
          - { label: "Cover Image", name: "cover_image", widget: "image", required: false }

  - name: "en-magic-powers"
    label: "Magic & Powers (EN)"
    folder: "en/wiki/magic-powers"
    create: true
    identifier_field: "slug"
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "URL-friendly version of the name" }
      - { label: "Summary", name: "summary", widget: "text", hint: "A brief description" }
      - { label: "Cover Image", name: "cover_image", widget: "image", required: false }
      - { label: "Public", name: "public", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

