backend:
  name: git-gateway
  branch: main

site_url: https://nimea-wiki.netlify.app

media_folder: "images"
public_folder: "/images"

# Simple publish mode - changes go live immediately
publish_mode: simple

collections:
  - name: "player-characters"
    label: "Player Characters"
    folder: "wiki/player-characters"
    create: true
    identifier_field: "slug"
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "URL-friendly version of the name" }
      - { label: "Summary", name: "summary", widget: "text", hint: "A brief description" }
      - { label: "Cover Image", name: "cover_image", widget: "image", required: false }
      - { label: "Public", name: "public", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "characters"
    label: "Characters"
    folder: "wiki/characters"
    create: true
    identifier_field: "slug"
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "URL-friendly version of the name" }
      - { label: "Summary", name: "summary", widget: "text", hint: "A brief description" }
      - { label: "Cover Image", name: "cover_image", widget: "image", required: false }
      - { label: "Public", name: "public", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "nations-factions"
    label: "Nations & Factions"
    folder: "wiki/nations-factions"
    create: true
    identifier_field: "slug"
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "URL-friendly version of the name" }
      - { label: "Summary", name: "summary", widget: "text", hint: "A brief description" }
      - { label: "Cover Image", name: "cover_image", widget: "image", required: false }
      - { label: "Public", name: "public", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "locations-regions"
    label: "Locations & Regions"
    folder: "wiki/locations-regions"
    create: true
    identifier_field: "slug"
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "URL-friendly version of the name" }
      - { label: "Summary", name: "summary", widget: "text", hint: "A brief description" }
      - { label: "Cover Image", name: "cover_image", widget: "image", required: false }
      - { label: "Map ID", name: "map_id", widget: "string", required: false, hint: "Link to map marker" }
      - { label: "Public", name: "public", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "gods-religions"
    label: "Gods & Religions"
    folder: "wiki/gods-religions"
    create: true
    identifier_field: "slug"
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "URL-friendly version of the name" }
      - { label: "Summary", name: "summary", widget: "text", hint: "A brief description" }
      - { label: "Cover Image", name: "cover_image", widget: "image", required: false }
      - { label: "Public", name: "public", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "magic-powers"
    label: "Magic & Powers"
    folder: "wiki/magic-powers"
    create: true
    identifier_field: "slug"
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "URL-friendly version of the name" }
      - { label: "Summary", name: "summary", widget: "text", hint: "A brief description" }
      - { label: "Cover Image", name: "cover_image", widget: "image", required: false }
      - { label: "Public", name: "public", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

