// Internationalization support - bilingual TR/EN UI

interface Translations {
  tr: Record<string, any>
  en: Record<string, any>
}

const translations: Translations = {
  tr: {
    addToRoute: 'Rotaya Ekle',
    clearRoute: 'Rotayı Temizle',
    showOnWiki: 'Külliyatta Gör',
    showOnMap: 'Haritada Göster',
    edit: 'Düzenle',
    delete: 'Sil',
    confirmDelete: 'işaretini silmek istediğine emin misin? Bu işlem geri alınamaz.',
    newMarker: 'Yeni İşaret Oluştur',
    markerName: 'Ad',
    markerId: 'Kimlik (ID)',
    markerType: 'Tür',
    markerIcon: 'Özel Simge',
    markerIconUrl: 'Veya Özel Görsel URL',
    markerFaction: 'Cemiyet/Devlet',
    autoGenerated: 'İsimden otomatik üretilir; düzenleyebilirsin',
    leaveEmpty: 'Varsayılan için boş bırak',
    customIcon: 'İstersen özel bir simge karakteri yazabilirsin',
    iconUrl: 'PNG/JPG bir simge URL\'si kullanabilirsin (yukarıdaki değerin yerine geçer)',
    types: {
      city: 'Şehir',
      town: 'Kasaba',
      village: 'Köy',
      fortress: 'Hisar',
      ruin: 'Harabe',
      landmark: 'Anıt',
      dungeon: 'Zindan',
      other: 'Diğer'
    }
  },
  en: {
    addToRoute: 'Add to Route',
    clearRoute: 'Clear Route',
    showOnWiki: 'View on Wiki',
    showOnMap: 'Show on Map',
    edit: 'Edit',
    delete: 'Delete',
    confirmDelete: 'marker? This action cannot be undone.',
    newMarker: 'Create New Marker',
    markerName: 'Name',
    markerId: 'ID',
    markerType: 'Type',
    markerIcon: 'Custom Icon',
    markerIconUrl: 'Or Custom Image URL',
    markerFaction: 'Faction/Nation',
    autoGenerated: 'Auto-generated from name; you can edit it',
    leaveEmpty: 'Leave empty for default',
    customIcon: 'You can enter a custom icon character if you want',
    iconUrl: 'You can use a PNG/JPG icon URL (replaces the above value)',
    types: {
      city: 'City',
      town: 'Town',
      village: 'Village',
      fortress: 'Fortress',
      ruin: 'Ruin',
      landmark: 'Landmark',
      dungeon: 'Dungeon',
      other: 'Other'
    }
  }
}

class I18n {
  private currentLang: 'tr' | 'en' = 'tr'

  /**
   * Initialize i18n system - detect language from URL
   */
  init(): void {
    // Detect language from URL path (/en/... vs /...)
    if (window.location.pathname.startsWith('/en')) {
      this.currentLang = 'en'
    }

    // Update document language attribute
    document.documentElement.lang = this.currentLang

    console.log(`✅ i18n initialized (language: ${this.currentLang})`)

    // Translate static content on page
    this.translateStaticContent()
  }

  /**
   * Get current language
   */
  getCurrentLang(): 'tr' | 'en' {
    return this.currentLang
  }

  /**
   * Set language and update UI
   */
  setLang(lang: 'tr' | 'en'): void {
    this.currentLang = lang
    document.documentElement.lang = lang
    this.translateStaticContent()
  }

  /**
   * Translate a key
   * @param key - Translation key
   * @param args - Optional arguments for string interpolation
   */
  t(key: string, ...args: any[]): string {
    let value = translations[this.currentLang][key]

    // Fallback to Turkish if not found
    if (!value) {
      value = translations.tr[key] || key
    }

    // Replace placeholders with arguments
    if (args.length > 0) {
      return args.reduce((str: string, arg: any, index: number) => {
        return str.replace(`{${index}}`, arg)
      }, value)
    }

    return value
  }

  /**
   * Get translated type label
   */
  getType(typeKey: string): string {
    if (!typeKey) return ''
    const typeMap = translations[this.currentLang].types || {}
    return typeMap[typeKey] || typeKey
  }

  /**
   * Translate static content in the DOM
   * Updates UI elements based on current language
   */
  private translateStaticContent(): void {
    // Update marker type select options
    const typeSelect = document.getElementById('marker-type')
    if (typeSelect) {
      const options = typeSelect.querySelectorAll('option')
      options.forEach((option: HTMLOptionElement) => {
        const value = option.value
        if (translations[this.currentLang].types[value]) {
          option.textContent = translations[this.currentLang].types[value]
        }
      })
    }

    // Translate form labels
    this.translateElement('marker-name-label', this.t('markerName'))
    this.translateElement('marker-id-label', this.t('markerId'))
    this.translateElement('marker-type-label', this.t('markerType'))
    this.translateElement('marker-icon-label', this.t('markerIcon'))
    this.translateElement('marker-icon-url-label', this.t('markerIconUrl'))
    this.translateElement('marker-faction-label', this.t('markerFaction'))

    // Translate buttons
    this.translateElement('add-to-route-btn', this.t('addToRoute'))
    this.translateElement('clear-route-btn', this.t('clearRoute'))

    // Translate modal headers
    this.translateElement('marker-modal-title', this.t('newMarker'))
  }

  /**
   * Update text content of an element by ID
   */
  private translateElement(id: string, text: string): void {
    const el = document.getElementById(id)
    if (el) {
      el.textContent = text
    }
  }

  /**
   * Load full i18n data from JSON file (for DM modules)
   * This loads extended translations for DM interface
   */
  async loadI18nData(): Promise<void> {
    try {
      const response = await fetch('/_data/i18n.json')
      const data = await response.json()
      ;(window as any).i18n = data // Expose for legacy DM modules if needed
      console.log('Extended i18n data loaded')
    } catch (error) {
      console.warn('Could not load _data/i18n.json, using inline translations:', error)
      // Fallback: use inline translations
      ;(window as any).i18n = { tr: translations.tr, en: translations.en }
    }
  }
}

// Export singleton instance
export const i18n = new I18n()

// Expose to window for legacy code compatibility
;(window as any).nimeaI18n = {
  t: (key: string, ...args: any[]) => i18n.t(key, ...args),
  getCurrentLang: () => i18n.getCurrentLang(),
  setLang: (lang: 'tr' | 'en') => i18n.setLang(lang),
  getType: (typeKey: string) => i18n.getType(typeKey)
}

// Auto-initialize when DOM is ready
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', () => {
    i18n.init()
    i18n.loadI18nData()
  })
} else {
  i18n.init()
  i18n.loadI18nData()
}
